format_version: 3
pipelines:
  pipeline-test:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/denislee/test
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - stage-first:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          job-first:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - README.md
                command: cat
                run_if: passed
